# Generated by Django 3.2.13 on 2022-06-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='location',
            new_name='geom',
        ),
    ]
