# Generated by Django 3.2.13 on 2022-06-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_rename_location_servicearea_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='geom',
            new_name='location',
        ),
    ]
